classDiagram
SoureApp --> Environment
SoureApp --> ContentConfiguration
SoureApp --> MojitoClaimManagement
MojitoClaimManagement --> MojitoCoreUI 
MojitoClaimManagement --> MojitoClaimService

class SoureApp {
    -JSON ContentConfiguration
    -Environment environment
    -MUITheme theme
    -Page page
}
class Environment {
    -String contentURL
    -String heroTemplate
    -String faqTemplate
    -String hostURL
}
class ContentConfiguration {
    -Object contentBlock
    -Object faq
    -Object basicTheme
}

class MojitoClaimService {
    -Library graphQL
    -Service hook
    -Interface ServiceData
    -ApolloApiProvider client
}

class MojitoClaimManagement {
    -Context configuration
    -Component Header
    -Component HeroBlock
    -Component HeroBlockContent
    -Component FAQ
    -Component FAQBlock
    -Component Footer
    -Component CreateWalletContainer
    -Component EnterCodeContainer
    -Component DiscountContainer
    -Component ClaimSuccess
    -Component ClaimLoading
    -Modal ClaimModal
    -Layout HomeLayout
    -Container HomeContainer
    -Library 
}

class MojitoCoreUI {
    -Component Breadcrumbs
    -Component TextInput
    -Component Button
    -Component Accordion
}