export const RuntimeConfiguration = {
  API_HOST_URL: process.env.NEXT_PUBLIC_RUNTIME_API_HOSTNAME!,
  CHAIN_ID: process.env.NEXT_PUBLIC_RUNTIME_CHAINID!,
  CROSSMINT_API: process.env.NEXT_PUBLIC_CROSSMINT_API_KEY,
  CROSSMINT_ENV: process.env.NEXT_PUBLIC_CROSSMINT_ENV,
  PAPER_CLIENT_ID: process.env.NEXT_PUBLIC_PAPER_CLIENT_ID,
  NETWORK_NAME: process.env.NEXT_PUBLIC_NETWORK_NAME,
  WALLET_CONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID ?? "",
  CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID ?? "",
  ACTIVE_CHAIN_ID: process.env.NEXT_PUBLIC_ACTIVE_CHAIN_ID ?? "sepolia",
};
