export const config = {
    API_HOST_URL: process.env.NEXT_PUBLIC_RUNTIME_API_HOSTNAME,
    CHAIN_ID: process.env.NEXT_PUBLIC_RUNTIME_CHAIN_ID,
    CROSSMINT_API: process.env.NEXT_PUBLIC_CROSSMINT_API_KEY,
    ORG_ID: process.env.NEXT_PUBLIC_ORG_ID,
    CROSSMINT_ENV: process.env.NEXT_PUBLIC_CROSSMINT_ENV,
    PAPER_CLIENT_ID: process.env.NEXT_PUBLIC_PAPER_CLIENT_ID,
    NETWORK_NAME: process.env.NEXT_PUBLIC_PAPER_NETWORK_NAME ?? 'Sepolia',
    WALLET_CONNECT_PROJECT_ID: process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID ?? '',
    CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID ?? '6d88de19e1a489546ad58e294c8dba4b',
    ACTIVE_CHAIN_ID: process.env.NEXT_PUBLIC_ACTIVE_CHAIN_ID ?? 'sepolia'
}